name: Deploy ClickOnce to GitHub Pages

on:
  push:
    branches:
      - deploy  # Il branch da cui vuoi fare il deploy

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v1

      - name: Build ClickOnce project
        run: |
          msbuild ItgManiaManager/ItgManiaManager.csproj /t:Publish /p:Configuration=Release /p:PublishDir=ItgManiaManager/ClickOnce/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ItgManiaManager/ClickOnce
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
